### ISSUE TITLE
Invoking undefined methods on `ServiceActor::Result` will lead to runtime errors in the next major release of Actor.

### ISSUE THREAD

**Issue by afuno** [sunny/actor#146] opened 2024-03-25 07:35 UTC
Hello.

After updating to version 3.8.0, a large number of project services in RSpec began to crash with this comment:

```
DEPRECATED: Invoking undefined methods on `ServiceActor::Result` will lead to runtime errors in the next major release of Actor.
```

In one of the examples, the service was mocked using `allow` and the expected result was indicated:

```ruby
allow(MyService).to(
  receive(:result)
    .and_return(
      ServiceActor::Result.new(failure?: true, error: "Some error")
    )
)
```

But at the same time, when actually checking the result of the service, the following data appears:

```ruby
service_result.failure?
# => false

service_result.success?
# => true
```

Please tell me what I'm doing wrong and what happened?

**Comment by afuno** [comment] 2024-03-25 07:38
Okay, I understand the change. Solution:

```ruby
ServiceActor::Result.new(failure: true, error: "Some error")
```

**Comment by afuno** [comment] 2024-03-25 08:45
This didn't actually solve the problem. There are a huge number of tests. Some of them were resolved through the example I gave above. But most tests continue to fail, for example with comments like this:

```
DEPRECATED: Invoking undefined methods on `ServiceActor::Result` will lead to runtime errors in the next major release of Actor. Invoked method: `public_send`
DEPRECATED: Invoking undefined methods on `ServiceActor::Result` will lead to runtime errors in the next major release of Actor. Invoked method: `public_send`
DEPRECATED: Invoking undefined methods on `ServiceActor::Result` will lead to runtime errors in the next major release of Actor. Invoked method: `public_send`
DEPRECATED: Invoking undefined methods on `ServiceActor::Result` will lead to runtime errors in the next major release of Actor. Invoked method: `public_send`
DEPRECATED: Invoking undefined methods on `ServiceActor::Result` will lead to runtime errors in the next major release of Actor. Invoked method: `object_id`
DEPRECATED: Invoking undefined methods on `ServiceActor::Result` will lead to runtime errors in the next major release of Actor. Invoked method: `object_id`
DEPRECATED: Invoking undefined methods on `ServiceActor::Result` will lead to runtime errors in the next major release of Actor. Invoked method: `instance_variables`
```

**Comment by viralpraxis** [comment] 2024-03-25 08:57
In general, I think it might make sense to add these methods in `ServiceActor::Result`. BTW @afuno what's the use-case for calling public_send/object_id/instance_variables on service result?

**Comment by afuno** [comment] 2024-03-25 08:58
> In general, I think it might make sense to add these methods in `ServiceActor::Result`. BTW @afuno what's the use-case for calling public_send/object_id/instance_variables on service result?

This is a deep dependence.

**Comment by sunny** [comment] 2024-03-25 09:01
I am guessing that those introspection methods are called by test-tooling like RSpec to build test doubles.

**Comment by viralpraxis** [comment] 2024-03-25 09:02
I'll open a PR soon if you don't mind @sunny 

@afuno Are there any other problematic methods generating warnings in your codebase?

**Comment by viralpraxis** [comment] 2024-03-25 09:08
> I am guessing that those introspection methods are called by test-tooling like RSpec to build test doubles.

We're using RSpec mocking actively but didn't encounter any warnings. But I'm pretty sure there are many gems/tools which don't paly nice with `BasicObject`, for example, `awesome_print`'s missing `Kernel#ai` breaks result introspection

**Comment by viralpraxis** [comment] 2024-03-25 09:17
@afuno Could please run your suite against https://github.com/sunny/actor/pull/148?

**Comment by afuno** [comment] 2024-03-25 09:23
Those problems are solved. But overall the problem is not solved. Next error:

```
NoMethodError: undefined method `expected' for an instance of RSpec::Matchers::BuiltIn::RaiseError
```

**Comment by viralpraxis** [comment] 2024-03-25 09:26
Could you please show some context of the error above? 🤔

**Comment by afuno** [comment] 2024-03-25 09:28
> Could you please show some context of the error above? 🤔

```ruby
it "..." do
  expect { perform(attributes:) }.to(
    raise_error(
      ApplicationService::Errors::Failure,
      "something went wrong"
    ).and(change(record, :column).from("some_1").to("some_2"))
  )
end
```

**Comment by afuno** [comment] 2024-03-25 09:29
> Could you please show some context of the error above? 🤔

Problem solved. It was about `failure?` and `failure`.

**Comment by afuno** [comment] 2024-03-25 09:32
I keep receiving a huge number of notifications like this:

```
DEPRECATED: Invoking undefined methods on `ServiceActor::Result` will lead to runtime errors in the next major release of Actor.
```

I can't give an example of method names, but there are many of them and they are different. All of them are related to the specifics of the project.

**Comment by viralpraxis** [comment] 2024-03-25 09:38
In general, if that's not a bug, that means that you are trying to invoke some method on `ServiceActor::Result` which was not defined as `output` in actor definition

**Comment by sunny** [comment] 2024-03-26 09:20
> The problems described above have been resolved.

You can use version `3.8.1` now, by the way.

**Comment by afuno** [comment] 2024-03-26 09:27
> @afuno Can you share with us one example of code that triggers this warning that you find unexpected? 🙏🏻

Unfortunately, I can't at the moment.



> > The problems described above have been resolved.
> 
> You can now use the newly-released v3.8.1, too.

---

But this does not solve the problem in total.

For now, I have fixed the `3.7` release line until better times. Unfortunately, at the moment I do not have time to understand hundreds of problems in tests.

**Comment by sunny** [comment] 2024-04-21 09:55
FYI 3.9.0 has been released with #153, which _could_ be related to your issues.

**Comment by afuno** [comment] 2024-04-22 05:49
@sunny Thanks for adding compatibility. Apparently, release 3.9 has fixed the problems described earlier.

However, there are still the following problems:

```
DEPRECATED: Invoking undefined methods on `ServiceActor::Result` will lead to runtime errors in the next major release of Actor. Invoked method: `title`
DEPRECATED: Invoking undefined methods on `ServiceActor::Result` will lead to runtime errors in the next major release of Actor. Invoked method: `nil?`
```

And what is most important is:

```
ArgumentError:
  input `error` overrides `ServiceActor::Result` instance method
```

Which reacts to this:

```ruby
input :error, type: String, allow_nil: true
```

**Comment by sunny** [comment] 2024-04-23 08:44
Thank you for reporting this back.

- For `#title`, the warning is here to encourage you to not call the method if the output has not been defined.

    For example you could make sure the result has succeeded _before_ calling `#title` on it, or you can even check if the `#title` method is defined.

- For `#nil?` I’ll add this to the default methods on results 👍🏻 

- For naming an input `error` I’ll make sure we can work around this 👍🏻

**Comment by sunny** [comment] 2024-04-23 08:55
@afuno I’ve fixed both `:errors` and `#nil?` issue. Can you try using the `main` branch and see if the only issue left on your code base are the warnings on `title`? 🙏🏻 

```rb
gem "service_actor", github: "sunny/actor", branch: "main"
```

**Comment by andrik** [comment] 2024-05-02 18:35
Hi @sunny 

I made a simple example extracted from README with the following configuration:

**Ruby**: 3.3.1
**Rails**: 7.1.3.2
**Actor**: 3.9.1
**Actor-Rails**: 1.0

I created a simple Actor

```ruby
class GreetUser < Actor
  input :name

  def call
    "Have a wonderful day, #{name}!"
  end
end
```

When I try to run the Actor on Rails console I get this output
![Xnip2024-05-02_15-30-16](https://github.com/sunny/actor/assets/239674/bd7c4eee-d94c-4bcf-8a19-a35c35a7cb78)

**Comment by sunny** [comment] 2024-05-02 19:51
Thank you for the report @andrik! Indeed the `#methods` method is used by introspection tools as well. I’ve merged #159 which should fix this. Can you try again from `main`, please? 🙏🏻

**Comment by andrik** [comment] 2024-05-02 20:44
Hi @sunny 

I tested and it worked.

![Xnip2024-05-02_17-43-16](https://github.com/sunny/actor/assets/239674/9f7c6e2d-db07-4f83-9298-1f45c64a4b72)

Thank you 🙏

**Comment by afuno** [comment] 2024-05-21 05:40
@sunny Hi. I checked version `3.9.1`. It still contains a large number of warnings. There is something simple:

```
DEPRECATED: Invoking undefined methods on `ServiceActor::Result` will lead to runtime errors in the next major release of Actor. Invoked method: `blank?`
```

But there is something more complicated when passing data to the `fail!` method.

**Comment by afuno** [comment] 2024-05-21 09:58
@sunny Can you please tell about the purpose of the latest releases and what are your plans for the future?

We have projects with a huge number of services. All these services were implemented in different styles, use wrappers, etc., which was not prohibited or limited by the Service Actor.

Over the last few releases of Service Actor, we have been experiencing problems with updating the library of various types. Now we don’t have a clear understanding of how the library should work, what is considered wrong, what has limitations, etc.

**Comment by sunny** [comment] 2024-05-21 17:11
Hi @afuno! Sorry to hear about those frustrations.

The changes that impact you come from using a slimmed down version of a Result instead of relying on Ruby’s deprecated OpenStruct. Therefore a lot of methods that you depended on don’t exist anymore and we need to bring them back in. I’m sorry about that.

Thank you for listing a few errors you are facing. I’ve noted:

- `blank?` method => allowed in #162
- `nil?` method => allowed in `main`
- `input :error` => allowed in `main`
- `private_methods` method => allowed in #162

Would you be willing to test your codebase against the `add-blank-method` branch to see if there are any other underlying issues? The codebases I use with actor don’t have the same gems or wrappers so I didn’t get to see the same issues come up.

```rb
gem "service_actor", github: "sunny/actor", branch: "add-blank-method"
```

**Comment by afuno** [comment] 2024-05-27 06:10
@sunny Apparently the problems that were described above have indeed been resolved. Thank you. Can you please make a release so I can finalize this in projects?

**Closed** 2024-05-27 14:23 UTC
Labels: bug
